In [57]:
import pandas as pd

In [58]:
data=pd.read_csv("Car_details(U).csv")
data.head()

,vehicle_uid,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,car_record_id,car_age,price_category,km_category,owner_count,fuel_transmission,brand,price_per_km,is_diesel
0,CAR_000001,Maruti 800 AC,2007,60000.0,70000.0,Petrol,Individual,Manual,First Owner,1,18,Low,NaN,0.0,Petrol_Manual,Maruti,0.86,0
1,CAR_000002,Maruti Wagon R LXI Minor,2007,135000.0,50000.0,NaN,Individual,Manual,First Owner,2,18,Low,NaN,0.0,Petrol_Manual,Maruti,2.70,0
2,CAR_000003,Hyundai Verna 1.6 SX,2012,600000.0,100000.0,Diesel,Individual,Manual,First Owner,3,13,NaN,NaN,NaN,Diesel_Manual,Hyundai,6.00,1
3,CAR_000004,Datsun RediGO T Option,2017,250000.0,46000.0,Petrol,Individual,Manual,First Owner,4,8,Low,Medium,0.0,Petrol_Manual,Datsun,5.43,0
4,CAR_000005,Honda Amaze VX i-DTEC,2014,450000.0,141000.0,Diesel,Individual,Manual,Second Owner,5,11,NaN,High,0.0,Diesel_Manual,Honda,3.19,1

# 1. Handling Missing Values in selling_price
Identify the maximum and minimum values of the selling_price column.    
Compute the average of these two values.                                         
Use this calculated average to fill all missing values in the selling_price column.

In [60]:
max_price = data["selling_price"].max()
max_price

8900000.0

In [61]:
min_price = data["selling_price"].min()
min_price

22000.0

In [62]:
avg = (max_price + min_price) / 2
avg

4461000.0

In [63]:
data["selling_price"]=data["selling_price"].fillna(avg)

In [64]:
data["selling_price"].isnull().any()

np.False_

# 2. Data Cleaning for km_driven and owner_count
Apply appropriate real-world data cleaning techniques to handle missing or inconsistent values in: 
(I)km_driven      
(II)owner_count  
Justify the chosen method for each column based on:    
(I)Data distribution   
(I)Practical real-world usage

In [66]:
data.describe()

,year,selling_price,km_driven,car_record_id,car_age,owner_count,price_per_km,is_diesel
count,4340.000000,4.340000e+03,3906.000000,4340.000000,4340.000000,3906.0,4340.000000,4340.000000
mean,2013.090783,9.027308e+05,66231.222990,2170.500000,11.909217,0.0,88.013984,0.496083
std,4.215344,1.311959e+06,47047.819626,1252.994413,4.215344,0.0,3801.519948,0.500042
min,1992.000000,2.200000e+04,1.000000,1.000000,5.000000,0.0,0.250000,0.000000
25%,2011.000000,2.250000e+05,35000.000000,1085.750000,9.000000,0.0,2.620000,0.000000
50%,2014.000000,4.000000e+05,60000.000000,2170.500000,11.000000,0.0,6.000000,0.000000
75%,2016.000000,7.500000e+05,90000.000000,3255.250000,14.000000,0.0,15.555000,1.000000
max,2020.000000,8.900000e+06,806599.000000,4340.000000,33.000000,0.0,250000.000000,1.000000

In [67]:
data["km_driven"].median()

60000.0

In [68]:
data["km_driven"]=data["km_driven"].fillna(data["km_driven"].median())

In [69]:
data["owner_count"].isnull().sum()

np.int64(434)

In [70]:
data["owner_count"].mode()

0    0.0
Name: owner_count, dtype: float64

In [71]:
data["owner_count"] = data["owner_count"].fillna(data["owner_count"].mode()[0])

In [72]:
print(data["owner_count"].isnull().sum())

0

# 3. Handling Missing Values in km_category                   
Fill 50% of missing values with the most frequent category (mode).      
Fill the remaining 50% of missing values with value "High".

In [73]:
data["km_category"].isnull().sum()

np.int64(434)

In [74]:
mode=data["km_category"].mode()
mode

0    Medium
Name: km_category, dtype: object

In [75]:
data["km_category"]=data["km_category"].fillna(mode[0],limit=217)

In [76]:
data["km_category"].isnull().sum()

np.int64(217)

In [77]:
data["km_category"]=data["km_category"].fillna("high",limit=217)

In [78]:
data["km_category"].isnull().sum()

np.int64(0)

# # 4. Handling Missing Values in price_category     
Fill missing values using the most frequent category (mode).       
If it is unclear whether the category is manually or automatically generated, replace missing values with "Unknown".

In [79]:
mode=data["price_category"].mode()
mode

0    Low
Name: price_category, dtype: object

In [80]:
data["price_category"]=data["price_category"].fillna(mode[0])

In [81]:
data["price_category"].isnull().any()

np.False_

In [82]:
data["transmission"]=data["transmission"].fillna("unknown")

In [83]:
data.isnull().any()

vehicle_uid          False
name                 False
year                 False
selling_price        False
km_driven            False
fuel                  True
seller_type          False
transmission         False
owner                False
car_record_id        False
car_age              False
price_category       False
km_category          False
owner_count          False
fuel_transmission    False
brand                False
price_per_km         False
is_diesel            False
dtype: bool

# 5. Handling Missing Values in fuel    
Distribute all missing values equally among existing unique fuel types.     
Ensure that each fuel type receives an equal number of assigned values.

In [84]:
data["fuel"].unique()

array(['Petrol', nan, 'Diesel', 'CNG', 'LPG', 'Electric'], dtype=object)

In [85]:
data["fuel"].isnull().sum()

np.int64(435)

In [86]:
435/5

87.0

In [87]:
data["fuel"]=data["fuel"].fillna("Petrol",limit=87)

In [88]:
data["fuel"]=data["fuel"].fillna("Diesel",limit=87)

In [89]:
data["fuel"]=data["fuel"].fillna("CNG",limit=87)

In [90]:
data["fuel"]=data["fuel"].fillna("LPG",limit=87)

In [91]:
data["fuel"]=data["fuel"].fillna("Electric",limit=87)

In [92]:
data["fuel"].isnull().sum()

np.int64(0)

In [93]:
data.isnull().any()

vehicle_uid          False
name                 False
year                 False
selling_price        False
km_driven            False
fuel                 False
seller_type          False
transmission         False
owner                False
car_record_id        False
car_age              False
price_category       False
km_category          False
owner_count          False
fuel_transmission    False
brand                False
price_per_km         False
is_diesel            False
dtype: bool

# 6. Exporting the Cleaned Dataset      
After completing all data cleaning steps:        
Split the final cleaned dataset into two separate CSV files.        
Export both files for further use.

In [94]:
data.to_csv("capstone1.csv",index=False)

In [95]:
data[["vehicle_uid","name","year","fuel",	"seller_type",	"transmission"	,"owner"	,"brand"	,"car_age"]].to_csv("vehicle_info.csv",index=False)

In [96]:
pwd

'C:\\Users\\Dell\\python class'

In [97]:
data[["vehicle_uid","selling_price","km_driven","price_category",	"km_category"]].to_csv("vehicle_sales.csv",index=False)

In [98]:
pwd

'C:\\Users\\Dell\\python class'